/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ClientCalendarRouteImport } from './routes/client.calendar'
import { Route as ClientCheckInsRouteImport } from './routes/client.check-ins'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as ClientMeetingsRouteImport } from './routes/client.meetings'
import { Route as ClientMessagesRouteImport } from './routes/client.messages'
import { Route as ClientNutritionRouteImport } from './routes/client.nutrition'
import { Route as ClientProgressRouteImport } from './routes/client.progress'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientTodayRouteImport } from './routes/client.today'
import { Route as ClientWeekRouteImport } from './routes/client.week'
import { Route as ClientWorkoutsRouteImport } from './routes/client.workouts'
import { Route as CoachCheckInsRouteImport } from './routes/coach.check-ins'
import { Route as CoachClientsRouteImport } from './routes/coach.clients'
import { Route as CoachDashboardRouteImport } from './routes/coach.dashboard'
import { Route as CoachMeetingsRouteImport } from './routes/coach.meetings'
import { Route as CoachMessagesRouteImport } from './routes/coach.messages'
import { Route as CoachNutritionRouteImport } from './routes/coach.nutrition'
import { Route as CoachProgressRouteImport } from './routes/coach.progress'
import { Route as CoachScheduleRouteImport } from './routes/coach.schedule'
import { Route as CoachSettingsRouteImport } from './routes/coach.settings'
import { Route as CoachVideosRouteImport } from './routes/coach.videos'
import { Route as CoachWorkoutsRouteImport } from './routes/coach.workouts'
import { Route as CoachClientsIdRouteImport } from './routes/coach.clients_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCalendarRoute = ClientCalendarRouteImport.update({
  id: '/client/calendar',
  path: '/client/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCheckInsRoute = ClientCheckInsRouteImport.update({
  id: '/client/check-ins',
  path: '/client/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMeetingsRoute = ClientMeetingsRouteImport.update({
  id: '/client/meetings',
  path: '/client/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/client/messages',
  path: '/client/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientNutritionRoute = ClientNutritionRouteImport.update({
  id: '/client/nutrition',
  path: '/client/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProgressRoute = ClientProgressRouteImport.update({
  id: '/client/progress',
  path: '/client/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/client/settings',
  path: '/client/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTodayRoute = ClientTodayRouteImport.update({
  id: '/client/today',
  path: '/client/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientWeekRoute = ClientWeekRouteImport.update({
  id: '/client/week',
  path: '/client/week',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientWorkoutsRoute = ClientWorkoutsRouteImport.update({
  id: '/client/workouts',
  path: '/client/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachCheckInsRoute = CoachCheckInsRouteImport.update({
  id: '/coach/check-ins',
  path: '/coach/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachClientsRoute = CoachClientsRouteImport.update({
  id: '/coach/clients',
  path: '/coach/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/coach/dashboard',
  path: '/coach/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMeetingsRoute = CoachMeetingsRouteImport.update({
  id: '/coach/meetings',
  path: '/coach/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMessagesRoute = CoachMessagesRouteImport.update({
  id: '/coach/messages',
  path: '/coach/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachNutritionRoute = CoachNutritionRouteImport.update({
  id: '/coach/nutrition',
  path: '/coach/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgressRoute = CoachProgressRouteImport.update({
  id: '/coach/progress',
  path: '/coach/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachScheduleRoute = CoachScheduleRouteImport.update({
  id: '/coach/schedule',
  path: '/coach/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/coach/settings',
  path: '/coach/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachVideosRoute = CoachVideosRouteImport.update({
  id: '/coach/videos',
  path: '/coach/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachWorkoutsRoute = CoachWorkoutsRouteImport.update({
  id: '/coach/workouts',
  path: '/coach/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachClientsIdRoute = CoachClientsIdRouteImport.update({
  id: '/coach/clients_/$id',
  path: '/coach/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/check-ins': typeof ClientCheckInsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/meetings': typeof ClientMeetingsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/nutrition': typeof ClientNutritionRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/today': typeof ClientTodayRoute
  '/client/week': typeof ClientWeekRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/coach/check-ins': typeof CoachCheckInsRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/meetings': typeof CoachMeetingsRoute
  '/coach/messages': typeof CoachMessagesRoute
  '/coach/nutrition': typeof CoachNutritionRoute
  '/coach/progress': typeof CoachProgressRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/coach/videos': typeof CoachVideosRoute
  '/coach/workouts': typeof CoachWorkoutsRoute
  '/coach/clients/$id': typeof CoachClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/check-ins': typeof ClientCheckInsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/meetings': typeof ClientMeetingsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/nutrition': typeof ClientNutritionRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/today': typeof ClientTodayRoute
  '/client/week': typeof ClientWeekRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/coach/check-ins': typeof CoachCheckInsRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/meetings': typeof CoachMeetingsRoute
  '/coach/messages': typeof CoachMessagesRoute
  '/coach/nutrition': typeof CoachNutritionRoute
  '/coach/progress': typeof CoachProgressRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/coach/videos': typeof CoachVideosRoute
  '/coach/workouts': typeof CoachWorkoutsRoute
  '/coach/clients/$id': typeof CoachClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/check-ins': typeof ClientCheckInsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/meetings': typeof ClientMeetingsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/nutrition': typeof ClientNutritionRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/today': typeof ClientTodayRoute
  '/client/week': typeof ClientWeekRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/coach/check-ins': typeof CoachCheckInsRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/meetings': typeof CoachMeetingsRoute
  '/coach/messages': typeof CoachMessagesRoute
  '/coach/nutrition': typeof CoachNutritionRoute
  '/coach/progress': typeof CoachProgressRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/coach/videos': typeof CoachVideosRoute
  '/coach/workouts': typeof CoachWorkoutsRoute
  '/coach/clients_/$id': typeof CoachClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/client/calendar'
    | '/client/check-ins'
    | '/client/dashboard'
    | '/client/meetings'
    | '/client/messages'
    | '/client/nutrition'
    | '/client/progress'
    | '/client/settings'
    | '/client/today'
    | '/client/week'
    | '/client/workouts'
    | '/coach/check-ins'
    | '/coach/clients'
    | '/coach/dashboard'
    | '/coach/meetings'
    | '/coach/messages'
    | '/coach/nutrition'
    | '/coach/progress'
    | '/coach/schedule'
    | '/coach/settings'
    | '/coach/videos'
    | '/coach/workouts'
    | '/coach/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/client/calendar'
    | '/client/check-ins'
    | '/client/dashboard'
    | '/client/meetings'
    | '/client/messages'
    | '/client/nutrition'
    | '/client/progress'
    | '/client/settings'
    | '/client/today'
    | '/client/week'
    | '/client/workouts'
    | '/coach/check-ins'
    | '/coach/clients'
    | '/coach/dashboard'
    | '/coach/meetings'
    | '/coach/messages'
    | '/coach/nutrition'
    | '/coach/progress'
    | '/coach/schedule'
    | '/coach/settings'
    | '/coach/videos'
    | '/coach/workouts'
    | '/coach/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/client/calendar'
    | '/client/check-ins'
    | '/client/dashboard'
    | '/client/meetings'
    | '/client/messages'
    | '/client/nutrition'
    | '/client/progress'
    | '/client/settings'
    | '/client/today'
    | '/client/week'
    | '/client/workouts'
    | '/coach/check-ins'
    | '/coach/clients'
    | '/coach/dashboard'
    | '/coach/meetings'
    | '/coach/messages'
    | '/coach/nutrition'
    | '/coach/progress'
    | '/coach/schedule'
    | '/coach/settings'
    | '/coach/videos'
    | '/coach/workouts'
    | '/coach/clients_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ClientCalendarRoute: typeof ClientCalendarRoute
  ClientCheckInsRoute: typeof ClientCheckInsRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientMeetingsRoute: typeof ClientMeetingsRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientNutritionRoute: typeof ClientNutritionRoute
  ClientProgressRoute: typeof ClientProgressRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientTodayRoute: typeof ClientTodayRoute
  ClientWeekRoute: typeof ClientWeekRoute
  ClientWorkoutsRoute: typeof ClientWorkoutsRoute
  CoachCheckInsRoute: typeof CoachCheckInsRoute
  CoachClientsRoute: typeof CoachClientsRoute
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachMeetingsRoute: typeof CoachMeetingsRoute
  CoachMessagesRoute: typeof CoachMessagesRoute
  CoachNutritionRoute: typeof CoachNutritionRoute
  CoachProgressRoute: typeof CoachProgressRoute
  CoachScheduleRoute: typeof CoachScheduleRoute
  CoachSettingsRoute: typeof CoachSettingsRoute
  CoachVideosRoute: typeof CoachVideosRoute
  CoachWorkoutsRoute: typeof CoachWorkoutsRoute
  CoachClientsIdRoute: typeof CoachClientsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/calendar': {
      id: '/client/calendar'
      path: '/client/calendar'
      fullPath: '/client/calendar'
      preLoaderRoute: typeof ClientCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/check-ins': {
      id: '/client/check-ins'
      path: '/client/check-ins'
      fullPath: '/client/check-ins'
      preLoaderRoute: typeof ClientCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/meetings': {
      id: '/client/meetings'
      path: '/client/meetings'
      fullPath: '/client/meetings'
      preLoaderRoute: typeof ClientMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/client/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/nutrition': {
      id: '/client/nutrition'
      path: '/client/nutrition'
      fullPath: '/client/nutrition'
      preLoaderRoute: typeof ClientNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/progress': {
      id: '/client/progress'
      path: '/client/progress'
      fullPath: '/client/progress'
      preLoaderRoute: typeof ClientProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/client/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/today': {
      id: '/client/today'
      path: '/client/today'
      fullPath: '/client/today'
      preLoaderRoute: typeof ClientTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/week': {
      id: '/client/week'
      path: '/client/week'
      fullPath: '/client/week'
      preLoaderRoute: typeof ClientWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/workouts': {
      id: '/client/workouts'
      path: '/client/workouts'
      fullPath: '/client/workouts'
      preLoaderRoute: typeof ClientWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/check-ins': {
      id: '/coach/check-ins'
      path: '/coach/check-ins'
      fullPath: '/coach/check-ins'
      preLoaderRoute: typeof CoachCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/clients': {
      id: '/coach/clients'
      path: '/coach/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof CoachClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/dashboard': {
      id: '/coach/dashboard'
      path: '/coach/dashboard'
      fullPath: '/coach/dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/meetings': {
      id: '/coach/meetings'
      path: '/coach/meetings'
      fullPath: '/coach/meetings'
      preLoaderRoute: typeof CoachMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/messages': {
      id: '/coach/messages'
      path: '/coach/messages'
      fullPath: '/coach/messages'
      preLoaderRoute: typeof CoachMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/nutrition': {
      id: '/coach/nutrition'
      path: '/coach/nutrition'
      fullPath: '/coach/nutrition'
      preLoaderRoute: typeof CoachNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/progress': {
      id: '/coach/progress'
      path: '/coach/progress'
      fullPath: '/coach/progress'
      preLoaderRoute: typeof CoachProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/schedule': {
      id: '/coach/schedule'
      path: '/coach/schedule'
      fullPath: '/coach/schedule'
      preLoaderRoute: typeof CoachScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/settings': {
      id: '/coach/settings'
      path: '/coach/settings'
      fullPath: '/coach/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/videos': {
      id: '/coach/videos'
      path: '/coach/videos'
      fullPath: '/coach/videos'
      preLoaderRoute: typeof CoachVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/workouts': {
      id: '/coach/workouts'
      path: '/coach/workouts'
      fullPath: '/coach/workouts'
      preLoaderRoute: typeof CoachWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/clients_/$id': {
      id: '/coach/clients_/$id'
      path: '/coach/clients/$id'
      fullPath: '/coach/clients/$id'
      preLoaderRoute: typeof CoachClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ClientCalendarRoute: ClientCalendarRoute,
  ClientCheckInsRoute: ClientCheckInsRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientMeetingsRoute: ClientMeetingsRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientNutritionRoute: ClientNutritionRoute,
  ClientProgressRoute: ClientProgressRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientTodayRoute: ClientTodayRoute,
  ClientWeekRoute: ClientWeekRoute,
  ClientWorkoutsRoute: ClientWorkoutsRoute,
  CoachCheckInsRoute: CoachCheckInsRoute,
  CoachClientsRoute: CoachClientsRoute,
  CoachDashboardRoute: CoachDashboardRoute,
  CoachMeetingsRoute: CoachMeetingsRoute,
  CoachMessagesRoute: CoachMessagesRoute,
  CoachNutritionRoute: CoachNutritionRoute,
  CoachProgressRoute: CoachProgressRoute,
  CoachScheduleRoute: CoachScheduleRoute,
  CoachSettingsRoute: CoachSettingsRoute,
  CoachVideosRoute: CoachVideosRoute,
  CoachWorkoutsRoute: CoachWorkoutsRoute,
  CoachClientsIdRoute: CoachClientsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
